export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const LOG_OUT = 'LOG_OUT'

export const REFRESHING_USERS = 'REFRESHING_USERS'
export const LOADING_USERS = 'LOADING_USERS'
export const UPDATE_USERS = 'UPDATE_USERS'
export const UPDATE_USERS_ERROR = 'UPDATE_USERS_ERROR'

