export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const LOG_OUT = 'LOG_OUT'

export const UPDATE_DASHBOARD = 'UPDATE_DASHBOARD'
export const LOADING_DASHBOARD = 'LOADING_DASHBOARD'
export const LOADING_DASHBOARD_ERROR = 'LOADING_DASHBOARD_ERROR'

export const UPDATE_UPCOMING_AUCTIONS = 'UPDATE_UPCOMING_AUCTIONS'
export const LOADING_UPCOMING_AUCTIONS = 'LOADING_UPCOMING_AUCTIONS'
export const LOADING_UPCOMING_AUCTIONS_ERROR = 'LOADING_UPCOMING_AUCTIONS_ERROR'

export const UPDATE_AUCTIONEER_DETAIL = 'UPDATE_AUCTIONEER_DETAIL'
export const LOADING_DETAIL_ERROR = 'LOADING_DETAIL_ERROR'


export const UPDATE_COMPLETED_AUCTIONS = 'UPDATE_COMPLETED_AUCTIONS'
export const LOADING_COMPLETED_AUCTIONS = 'LOADING_COMPLETED_AUCTIONS'
export const LOADING_COMPLETED_AUCTIONS_ERROR = 'LOADING_COMPLETED_AUCTIONS_ERROR'

export const UPDATE_AWAITING_AUCTIONS = 'UPDATE_AWAITING_AUCTIONS'
export const LOADING_AWAITING_AUCTIONS = 'LOADING_AWAITING_AUCTIONS'
export const LOADING_AWAITING_AUCTIONS_ERROR = 'LOADING_AWAITING_AUCTIONS_ERROR'

